### ISSUE TITLE
Simple frontend UI to fetch and display article and metadata.

### ISSUE THREAD

**Issue by vincentdavis** [vincentdavis/newspaper_ab#2]
Need a simple UI that allows a visitor to paste a URL into a text field. Then using the newspapers api, fetch the article and all the structured data provided by the newspaper api.
Display this data on the page.

Record to the database all resulted URLS and if the URL was valid or not, date time, IP address.

**Comment by theirfanirfi** [comment]
[NewsPaper.zip](https://github.com/vincentdavis/newspaper_ab/files/2307558/NewsPaper.zip)
Done.
