### ISSUE TITLE
Implement Annotation Milestone 

### ISSUE THREAD

**Issue by vincentdavis** [vincentdavis/newspaper_ab#3]
Want to be able to select text in the TEXT filed and add a comment (Annotation) 
The UI Allows the user to select the text, Clicks an annotate button. The user then has to following fields. 
**Field** names: description 
**SUBJECT**: text field. A short description of the annotation. 
**TYPE**: select from list [False, Opinion, Speculation, Scientific theory] 
**ANNOTATION COMMENT**: long text field
**SUPPORTING URLS**: Allow a user to add up to 5 URLS. 

All of this is a very simple UI Record the data to the database and every time this news URL is loaded, Show the highlighted text and then list if Annotations.

**Comment by theirfanirfi** [comment]
done. 
http://heteroskedastic2.pythonanywhere.com/
